### ISSUE TITLE
Review Backup Policy of Discourse

### ISSUE THREAD

**Issue by nielx** [haiku/infrastructure#108]
The current discourse volume has a size of 16 GiB. Discourse has an automated backup tool, which makes a backup of all the data in the database, as well as all attachments. That backup is now at 2.2 GB. 

The current configuration is to do a backup every 2 days, and to keep a maximum of 4 backups at a time. However, since about the end of November, the system has been unable to create any new backups. 

For now, I have deleted two backups, which would allow the system to create a new backup on its regular schedule soon.

We have a few options for the future:

- Increase the size of the persistent volume. I have been unable to determine a cost so far, but it should be affordable.
- Decrease the number of backups that Discourse keeps.

Note that we are not exclusively reliant on the internal backup system: we have daily (?) jobs to make a backup of the volume and the postgres database as well.

**Comment by kallisti5** [comment]
I'd say just cut it down to 2 backups.    These in-discourse backups cover the attachments and on-disk data.  We also have our standard encrypted backups which cover postgresql for discourse.

**Comment by nielx** [comment]
Done.
