### ISSUE TITLE
[concourse] No new nightly images since Feb 13.

### ISSUE THREAD

**Issue by OscarL** [haiku/infrastructure#114]
Expected behavior: builds trigger once a day (ideally, only if there has been any new commit at all, see issue #76).

**Comment by kallisti5** [comment]
restarted my worker. Looks like concourse lost connection to all workers.

**Comment by kallisti5** [comment]
ok, I have a fix in.    A builder came back online from a remote location, however wasn't working properly.  I added the ability to target sites which fixed this one.
