### ISSUE TITLE
Request for Masked HDS Databsae Dump

### ISSUE THREAD

**Issue by andponlin** [haiku/infrastructure#116]
Hello; could I please get another **masked** dump of the HDS database as I am going to be applying some migrations in the next version of HDS which are a bit complex and would like to be more sure that they will work at deploy time. Thank you!

**Comment by nielx** [comment]
What's the output format you want from pg_dump? And where can I find your public PGP key?

**Comment by andponlin** [comment]
Hello @nielx; I have sent the GPG key in a separate message. The `pg_dump` "script" format please.

**Comment by nielx** [comment]
Database dump provided.

**Comment by nielx** [comment]
FYI I added a template to request a database dump too. Hopefully will streamline requests in the future :-P
