### ISSUE TITLE
Haiku Depot Server Setup for R1B5

### ISSUE THREAD

**Issue by andponlin** [haiku/infrastructure#131]
The R1B5 setup needs to be made in Haiku Depot Server (HDS). The additional Identifiers you will need are;

|HDSRepository Code|HDS Repository Source Code|Extra Identifier for R1B5|
|---|---|---|
|`haikuports`|`haikuports_x64_64`|`tag:haiku-os.org,2001:repositories/haiku/r1beta5/x86_64`|
|`haikuports`|`haikuports_x86_gcc2`|`tag:haiku-os.org,2001:repositories/haiku/r1beta5/x86_gcc2`|

Steps to add the additional R1B5 identifier;

- Authenticate as an admin users with HDS
- Navigate to the list of Repositories
- Click on HaikuPorts
- Click on `haikuports_x86_64` Source
- Edit and add the extra identifier
- Save Changes

Do the same thing for the `haikuports_x86_gcc2` Source.

To confirm the change has worked, load an R1B5 system, load HaikuDepot (desktop application) and observe that the "Featured Packages" are populated.

**Comment by waddlesplash** [comment]
But actually I think this was a misconfiguration on my part. R1beta5 should use `master` identifier tag still as that's what the HaikuPorts repository uses. So I should just fix the name in the beta branch.

**Comment by andponlin** [comment]
> R1beta5 should use master identifier tag still as that's what the HaikuPorts repository uses.

OK thanks for the clarification -- if that's the case then can you close this ticket please?

> Hmm, why aren't you an admin user of HDS?

I used to have application and deployment admin access back when it was running on a VM, but when it moved to K8S, the admin group switched to management of the the deployment and application. Maybe application management access at the application level makes sense, but probably not the deployment level?

**Comment by waddlesplash** [comment]
Making your user have admin access at least to the web console would make sense. It seems I don't have it either. What do I need to do to get/give it?

**Comment by andponlin** [comment]
> What do I need to do to get/give it?

Open a `psql` (Postgres) database connection to the HDS database and run the following commands exchanging the `xxxxxxxxxxxx` with your nickname.

```
BEGIN;
UPDATE haikudepot.user SET is_root = true WHERE nickname = 'xxxxxxxxxxxx';
COMMIT;
```

To be sure; observe that the `UPDATE` statement above has only altered a single row before proceeding with the `COMMIT` statement.

**Comment by andponlin** [comment]
@waddlesplash has indicated it is a config issue on the repo side.
