### ISSUE TITLE
Haiku Depot Server: Granting permissions and CSV upload

### ISSUE THREAD

**Issue by humdingerb** [haiku/infrastructure#132]
Not sure this is the place for this, but we can't seem to get a hold of an HDS admin... :)

1. Michel Clasquin-Johnson would like to help out keeping the "Featured packages" updated and maintain categories etc., see [his post at haiku-depot-web](https://www.freelists.org/post/haiku-depot-web/Featured-Apps). He'd need his permissions at HDS elevated accordingly.
2.  [Trac ticket #18953](https://dev.haiku-os.org/ticket/18953) has an attachment to change the category of all font packages from "Graphics" to "Fonts": [hds_pkgcategory_fonts.csv](https://dev.haiku-os.org/attachment/ticket/18953/hds_pkgcategory_fonts.csv)     
Could someone upload that to HDS, please?

No. 1 up there would be nice to get done quickly, so Michel can get to work before beta5 hits.
Thanks!

**Comment by waddlesplash** [comment]
1. Done.
2. HDS emits an error, I commented on the ticket. Further discussion can occur there.
