### ISSUE TITLE
buildbot.haiku-os.org certificate expired.

### ISSUE THREAD

**Issue by anevilyak** [haiku/infrastructure#17]
Buildbot's certificate appears to have expired:

NET::ERR_CERT_DATE_INVALID
Subject: buildbot.haiku-os.org
Issuer: Let's Encrypt Authority X3
Expires on: Apr 8, 2018
Current date: Apr 16, 2018

**Comment by nielx** [comment]
Buildbot is still running on vmdev. The certificate has been renewed now and is valid until July 28th 2018. I expect buildbot to be migrated by then.

**Comment by kallisti5** [comment]
>  The certificate has been renewed now and is valid until July 28th 2018.

Thanks!!!!!


> I expect buildbot to be migrated by then.

I thought the same thing last time I hand-renewed it :-)
