### ISSUE TITLE
Finish i18n migration

### ISSUE THREAD

**Issue by nielx** [haiku/infrastructure#18]
- [x] Pootle: Have the build fix for musl reviewed (nielx)
- [x] Pootle: Set up repository push access for updated translations 
- [x] Pootle: Check the synchronization script
- [x] Userguide: Check the functionality of the userguide tool
- [x] Userguide: Check 404
- [x] Pootle: Set up a weekly cron job to synchronize everything
- [x] Pootle/userguide: use pg_dump to periodically dump the db

**Comment by nielx** [comment]
First step: https://review.haiku-os.org/#/c/132/

**Comment by nielx** [comment]
There is an updated synchronization script currently active.

**Comment by nielx** [comment]
Cron job done in https://github.com/haiku/infrastructure/commit/0fc17aaf95bcd5d5874d3acb8482315559797d8e

**Comment by jt15s** [comment]
Has this been fully completed yet?

**Comment by nielx** [comment]
Assigning to me. The leftover work is to create jobs to backup the database and volumes.

**Comment by nielx** [comment]
Backup jobs have been deployed; this ticket will be closed once they have successfully run once

**Comment by nielx** [comment]
Jobs have run successfully

```
pootle-pgbackup-28526400                   1/1           4m34s      3d8h
pootle-pvbackup-28526460                   1/1           20m        3d7h
userguide-pgbackup-28526400                1/1           37s        3d8h
userguide-pvbackup-28526460                1/1           7m32s      3d7h
```
