### ISSUE TITLE
Buildbot is *unbelievably* slow after adding the 4 new workers

### ISSUE THREAD

**Issue by waddlesplash** [haiku/infrastructure#36]
Running htop on Maui shows that it uses around 5-10% CPU for the main process, so it must be blocked on something else. Even the backend is slow: it was taking 30 seconds to start the next task after completing the prior one in some cases.

It looks like we still use SQLite for the database: https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg#L59

And per the documentation, it looks like quite a lot of stuff is stored in the database, and virtually all pages and build status stuff is stored and access from it: http://docs.buildbot.net/latest/developer/database.html

Indeed, they have some tickets about it: https://github.com/buildbot/buildbot/issues/3002

It looks like they support using a Postgres database instead. We should do that ASAP.

**Comment by kallisti5** [comment]
done
