### ISSUE TITLE
Pootle: import catkeys from buildbot

### ISSUE THREAD

**Issue by nielx** [haiku/infrastructure#37]
The current Pootle image is large (1.2 GB), because of all the build tools that are included in the image. In the previous setup the catkeys were generated by the build bots, and then imported into the system. I wish to return to this situation. 

Solving this would mean to define a way to import the files.

**Comment by waddlesplash** [comment]
A Clang install is only about 200MB including all dependencies, so why is it so large? We don't need the full cross compilers set now.

**Comment by nielx** [comment]
Can the catkeys be extracted without building the cross-compiler now (e.g. with running configure with the --host-only flag)?

**Comment by waddlesplash** [comment]
Host only will not work, but you do not need to build a separate cross compiler. Just install Clang and then --use-clang instead of --build-cross-tools. I've already changed the setup on Maui to use this.

**Comment by nielx** [comment]
Just to get back to the issue though, I think the function of the pootle instance should be to offer pootle, not to compile and generate catkeys.

**Comment by waddlesplash** [comment]
Well with Clang as I said, you do not need to compile anything, as clang ignores missing header files when using -E. I've already configured Jam to take advantage of this, and I modified the pootle script to only jam the catkeys without a full build.

**Comment by kallisti5** [comment]
During the nightly build under concourse, could we generate catkeys.zip and upload the latest to one of our s3 buckets?

**Comment by nielx** [comment]
This has now been implemented. Thanks @kallisti5 for the help!
