### ISSUE TITLE
Support for GitHub notifications is broken

### ISSUE THREAD

**Issue by Barrett17** [haiku/infrastructure#42]
Since a lot of time Haiku-infrastructure doesn't support GitHub notifications for developer branches anymore. Since creating branches is not allowed anymore due to gerrit, this needs to be fixed ASAP.

**Comment by Barrett17** [comment]
So, I want to fix this issue, can someone point out where to start?

**Comment by waddlesplash** [comment]
I think we actually will need a new container for this; the way it worked on vmrepo was to clone the git repo and add all GitHub branches as tracked refs. I grabbed the scripts at least, so I can probably post them somewhere.

**Comment by Barrett17** [comment]
Not willing to work on that anymore, sorry.
