### ISSUE TITLE
Allocate additional 30GiB data storage to each buildmaster

### ISSUE THREAD

**Issue by kenmays** [haiku/infrastructure#44]
Enhancement for an additional 30 GiB storage to each buildmaster.

- Buildmaster x86_gcc2
- Buildmaster x86_64

NOTE: Enhances build capacity for 'build everything' packaging of Haikuports.
Enhancement for: https://dev.haiku-os.org/ticket/14996

**Comment by kallisti5** [comment]
The buildmasters aren't limited on space (beyond what the server has)

We do however need additional space on @mmlr 's workers.

**Comment by mmlr** [comment]
The builders have 40GiB of storage and are half empty. Without looking at the code, I am reasonably sure that an out of space error on the builder would not make the buildrun status reflect that, so I say this was an issue on the buildmaster side.

In any case expanding storage of the builders isn't an option for me as the next size would be twice the cost and I'm paying these out of my own pocket.

Generally these brute force everything builds aren't a good way to do builds. As evidenced by the log, in case of secondary architectures, the blind scheduling of all possible ports will lead to thousands of invalid combinations being tried and skipped for no reason. I should have removed the everything mode back when I noticed that shortcoming but for some reason didn't.

A nicer way to handle missing ports is to build a list of valid packages (using `haikuporter --list-packages --print-filenames --active-versions-only`), subtract the list of existing packages to get a list of the missing packages and then translate that back to missing ports (using `haikuporter --ports-for-packages`). Arguably that process could be wrapped up in a direct command, especially when HaikuPorter is used to manage the package repository anyway.

To keep the buildrun size reasonable I would also suggest to schedule builds for the missing ports in batches of some limited size. This reduces the annoyances in case builders are lost and the buildrun has to be repeated.

The above is how I initially bootstrapped the package repositories when originally setting things up.

**Comment by kallisti5** [comment]
weird.. plenty of space available on buildmasters:

/dev/sdb1       1.0T  882G  139G  87% /var/lib/docker

(not *tons*, but enough)

**Comment by kenmays** [comment]
@mmlr - 2,975 packages for x86_gcc2 (missing packages listing) as of today.

**Comment by mmlr** [comment]
I'm not sure how you arrived at this number. Following the steps I outlined above and using the repository packages list at https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current/package.list (which is conveniently written out on each repository update), one arrives at 217 missing ports for x86_gcc2. and 41 for x86_64.

To make this simpler I've wrapped the above steps in a script here: https://github.com/haikuports/haikuporter/commit/96af04bcb8e2c49b1a33c1c87fcab05755b07edb

**Comment by kenmays** [comment]
Thanks. Based on the feedback - we have enough available free storage on the buildmaster(s) and builder(s) to handle the majority of the normal build loads from the main core developers and Haukuports maintainers.

The 'build everything/world' haikuporter-related storage-related issues are managed and handled as-needed (to lower overall costs).
