### ISSUE TITLE
Can't download commit-msg hook from Gerrit

### ISSUE THREAD

**Issue by KapiX** [haiku/infrastructure#45]
/Data/haiku> scp -p -P 29418 KapiX@git.haiku-os.org:hooks/commit-msg haiku/.git/hooks/
ssh: connect to host git.haiku-os.org port 29418: Connection refused

I'm guessing port 29418 is blocked.

**Comment by waddlesplash** [comment]
Gerrit SSH is on port 22, not 29418.

**Comment by KapiX** [comment]
![image](https://user-images.githubusercontent.com/686372/59151546-22028100-8a35-11e9-916c-34279137f6bf.png)

This is what gerrit gives you as command line to clone with the hook. And 29418 is a standard port for this (any other Gerrit instance I have encountered uses it). So something is definitely misconfigured on our end.

**Comment by kallisti5** [comment]
1) Gerrit *definitely* listening on 22. We did this to retain compatibility with everyone's clients when we switched over. Gerrit is internally listening on, but we present it over 22.
2) git.haiku-os.org, or review.haiku-os.org
3) All of [our documentation](https://www.haiku-os.org/guides/building/get-source-git) [on git](https://git.haiku-os.org/haiku/) shows (port 22)[https://www.haiku-os.org/documents/dev/building_haiku_ubuntu_linux_step_step/).

With all of that said...
* when you click download on a patchset, and click ssh the correct URL is given.
  * https://review.haiku-os.org/c/haiku/+/1302
  * Download -> SSH
* when you click to browse a repository, the *wrong* port is given
  * https://review.haiku-os.org/admin/repos/haiku

So, it sounds like a bug in Gerrit.

**Comment by kallisti5** [comment]
I grabbed our secret config file for gerrit and trimmed out the sensitive stuff. If you can find where gerrit is expecting an alternate url for that link, let me know...

```
[gerrit]
        basePath = git
        canonicalWebUrl = https://review.haiku-os.org/
        canonicalGitUrl = git://git.haiku-os.org
[index]
        type = LUCENE
[auth]
        type = OAUTH
        gitBasicAuthPolicy = HTTP
[receive]
        enableSignedPush = false
[sendemail]
        smtpServer = smtp
        smtpServerPort = 25
        enable = true
        html = true
        from = Gerrit <review@review.haiku-os.org>
        connectTimeout = 30
[container]
        user = gerrit2
        javaHome = /usr/lib/jvm/java-1.8-openjdk/jre
        heapLimit = 1024m
        javaOptions = "-Dflogger.backend_factory=com.google.common.flogger.backend.log4j.Log4jBackendFactory#getInstance"
        javaOptions = "-Dflogger.logging_context=com.google.gerrit.server.logging.LoggingContext#getInstance"
[sshd]
        listenAddress = *:29418
        advertisedAddress = git.haiku-os.org
[httpd]
        listenUrl = proxy-https://*:8080
[cache]
        directory = cache
[hooks]
        path = /var/gerrit/review_site/hooks
[oauth]
        allowRegisterNewEmail = true
        allowEditFullName = true
[plugins]
        allowRemoteAdmin = true
[gitweb]
        type = cgit
        url = http://cgit.haiku-os.org/
```

Maybe advertisedAddress needs a port number?

**Comment by leavengood** [comment]
I would guess Gerrit just prints out the listenAddress. It doesn't know it is in Docker, and that port 29418 is being mapped to port 22 on the outside. Why not have it listen on port 22 inside Docker too, and just map 22:22?

**Comment by leavengood** [comment]
Actually it does sound like changing advertisedAddress to add port 22 will work:

https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#sshd.advertisedAddress

I think this is where some confusion arises. In the first paragraph in the above it says:

>  In any form, :'port' may be omitted to use the default SSH port of 22.

But then at the end it says:

> By default uses the value of sshd.listenAddress.

And I guess, therefore, if you only have a "*:<port>" in `listenAddress`, it will combine that with the host in `advertisedAddress`? Pretty confusing.

**Comment by kallisti5** [comment]
> And I guess, therefore, if you only have a "*:[port]" in listenAddress, it will combine that with the host in advertisedAddress? Pretty confusing.

Welcome to Gerrit. The whole thing is a contradiction to itself :-)
