### ISSUE TITLE
HDS: update Haikuports import

### ISSUE THREAD

**Issue by kenmays** [haiku/infrastructure#50]
See: https://depot.haiku-os.org/#!/repository/haikuports?bcguid=bc614-WTUS
Last Import: 2019-09-04 13:18:29

**Comment by kallisti5** [comment]
I just manually triggered an import, and that date didn't change.     I just clicked into the repo, and it shows:
"Last Import 2019-10-18 16:17:30"

So, no idea what's going on.   HDS is supposed to technically self-manage repo imports now... so looks like a bug?

**Comment by kenmays** [comment]
Yes. I searched for 'kobodeluxe' just now and it was not found (found/appears in the HD client app).

NOTE: When I tried to submit a rating for kobodeluxe using the local client app, I get 'a requested object or an object involved in request was not found on the server.'  I can submit rating info using HDS for app info already imported.

Might be something stuck... ?

**Comment by kenmays** [comment]
HaikuDepot client app mentioned a remote database issue during a 'Ratings' submission. Similar process works when done through the HDS web interface. Database health check?

**Comment by kenmays** [comment]
Resolved:
HDS Version 1.0.116
Active | Code | Last Import
haikuports_x86_64 | 2020-04-06 13:17:55
haikuports_x86_gcc2 | 2020-04-06 13:18:46
