### ISSUE TITLE
Gerrit  2.16 EOL

### ISSUE THREAD

**Issue by nielx** [haiku/infrastructure#56]
According to the [Release Plan](https://www.gerritcodereview.com/2020-04-22-gerrit-3.2-release-plan.html) of Gerrit 3.2, the 2.16 release is EOL. This means we need to start looking into updating Gerrit at some point.

The possible targets could be:
 - Gerrit 3.0
 - Gerrit 3.1
 - Gerrit 3.2

Initial to do list:

- [ ] Review whether the target version works in WebPositive
- [ ] Create a list of plugins and review whether they work in the target version
- [ ] Review all repository-customizations (i.e. hook scripts) for possible incompatibilities
- [ ] Create an update plan, including backup
- [ ] Update!

**Comment by kallisti5** [comment]
We're already on 3.0.12.   We need to keep slowly moving towards 3.2 however.

**Comment by kallisti5** [comment]
We were upgraded to Gerrit 3.2
I think I have all of the upgrade issues resolved (hooks were not working, see https://github.com/haiku/infrastructure/commit/e85149b6386d68bca5d5fb14f6db7948f8316f78)

Users are reporting rendering issues in WebPositive... so an update to 3.4 might be in our near future to see if it resolves the issue.
