### ISSUE TITLE
cgit: Update to v1.2.4 Once Released

### ISSUE THREAD

**Issue by CodeforEvolution** [haiku/infrastructure#63]
The version of cgit that we are running is now about 2-3 years old, and is internally making use of a git version that is, correspondingly, 2-3 years old. We are currently running cgit v1.2.1 while the latest is v1.2.3.

While we could upgrade now, I see that a new release may be just around a corner. It may be worth waiting for this update, as it would bring the internal git version from 2.25.1 (released more than a year ago), to 2.31.0 (the latest release).

**Comment by nielx** [comment]
It should not be too difficult to update cgit, if we rebuild the image now it will go to version1.2.3. It maybe does warrant whether there are any changes in the functionality or the config that may be relevant for us.

**Comment by kallisti5** [comment]
We have been on 1.2.3 for a few months now. As of this writing 1.2.4 is still not released.   Lets re-open this one once cgit actually releases 1.2.4 :-)
