### ISSUE TITLE
Status Page for Infrastructure

### ISSUE THREAD

**Issue by jt15s** [haiku/infrastructure#72]
With all the different bits of web infrastructure all needing to be maintained/managed, it would be good if we had a status page so both users and admins can check the status of web infrastructure. Plus, for scheduled system maintenance, it would be good to have a location for sysadmins to issue maintenance notices.

Now, I did some research and there are two types of status pages:
1. "Static" status pages: generated using a static site generator like Hugo. These can be deployed using our existing Netlify plans and thus are relatively simple to set up. Mainly involves admins sending alerts for downtime, maintenance.
Options: https://github.com/cstate/cstate, https://marquez.co/statusfy, https://github.com/statsig-io/statuspage (with auto-monitoring), 
2. "Dynamic" status pages: dynamic pages, some even have auto-monitoring functions. May be more complex to set up.
Options: https://upptime.js.org/, https://github.com/Monitorr/Monitorr, https://github.com/valeriansaliou/vigil

We'll have to determine which type of status page is best for us and whether we need any features like notifications through email, Matrix etc.

**Comment by kallisti5** [comment]
"What am I, a joke to you?" -- http://status.haiku-os.org

**Comment by kallisti5** [comment]
By the way, the logo looks like crap because it was set before statuscake started requiring a paid plan to set a logo + customize the theme.  

Since requiring a paid plan, we can no longer "change it". 


![logo](https://user-images.githubusercontent.com/100110/132891655-e4ea3087-e186-4793-9b3a-9281c1b56e56.png)


Statuscake wants $24/month for monitoring now which everyone agrees is too much.

**Comment by jt15s** [comment]
@kallisti5 Yikes. A status page with no HTTPS (it's 2021, for goodness sake), no monitoring and no logo - and if we want to actually have monitoring, we have to fork out 24 bucks a month?! We definitely need to switch to something else - I've listed lots of options in my original post. They're all FOSS too.

**Comment by kallisti5** [comment]
any status page we choose needs to include external monitoring of services.  Anything self-hosted would need to be on our infrastructure kinda defeating the purpose of status monitoring :-)

In theory we could deploy a separate server in a different hosting provider somewhere, but that requires time / money /etc.

I'm open to a new status monitor (it's been on my lust of projects for a while), but ideally it should offer everything statuscake did before going paid-only-to-be-useful.

**Comment by kallisti5** [comment]
cstate looks interesting, but i really don't understand what is doing the monitoring... I guess it's just javascript checking the current status of various services from the user's browser without any historical tracking?

**Comment by jt15s** [comment]
@kallisti5 Some of the "static" status pages can be deployed through GitHub pages or Netlify so that makes it separate from the rest of our infrastructure. Cstate doesn't do auto-monitoring, I assume you're talking about Status Page? That runs a curl script every hour using GitHub Actions to check if a URL is online or not.
