### ISSUE TITLE
Investigate internal oauth server

### ISSUE THREAD

**Issue by kallisti5** [haiku/infrastructure#8]
review.haiku-os.org is dependent on Github.

Since git access is critical to our infrastructure, we may want to investigate deploying our own oauth server at some point.  We could begin to tie various services back to this common authentication gateway.

Github was an easy solution for the short term, but it makes us dependent on an external 3rd party service... are we ok with this?

**Comment by jt15s** [comment]
Sounds like a good idea - SSO for all Haiku services would make it so much easier. It's a lot of work but would unify all the different login systems plus let more people without a GitHub account contribute. Problem is to figure out how we will merge all the different accounts, passwords, emails etc - maybe we could research what other FOSS projects have done (i.e. KDE's login system).

I envision something akin to how Google works (i.e. an app drawer with all the apps and options to login/out on all Haiku-related websites/web apps).

**Comment by nielx** [comment]
Is it worthwhile investigating the cost for outsourcing this? Getting a service that hosts the authentication platform (and data), and offers advanced features like 2FA might be worth the cost, versus the risk of us loosing data...

**Comment by jt15s** [comment]
@nielx I think Netlify offers some sort of OAUTH service so that is one option, will have a look at others though.

**Comment by jt15s** [comment]
Hmm, Netlify's identity service is called Netlify Identity, but it's mainly just used to provide gated content etc. and is not a full OAUTH solution. 

I found this service called Auth0, it provides a free plan with up to 7000 active users and unlimited logins: https://auth0.com/
Pricing info here: https://auth0.com/pricing
If we go over this we can get a discount on paid plans through Haiku Inc.: https://auth0.com/social-impact/pricing

**Comment by jt15s** [comment]
There is also Amazon Cognito (part of AWS): https://aws.amazon.com/cognito/
Okta: https://www.okta.com/products/single-sign-on/
Ory: https://www.ory.sh/pricing/
Oauth.io: https://oauth.io/home/pricing

**Comment by waddlesplash** [comment]
I think the major point was to self-host an OAuth provider. The major reason to do this is because of users who want to avoid GitHub signins and the like. Using a third party service other than GitHub probably won't be much better in their eyes.

**Comment by jt15s** [comment]
@waddlesplash Ory is open-source: https://www.ory.sh/open-source/
Of course, there are also the usual options like Keycloak etc.

**Comment by jt15s** [comment]
@waddlesplash Ory is open-source: https://www.ory.sh/open-source/
Of course, there are the usual options like Keycloak, OpenID etc.

**Comment by kallisti5** [comment]
Keep in mind, anything we setup must be integrated with:

* Gerrit
* Discourse
* Trac

Anything setup *should* integrate with:

* i18n
* Haikudepot

Maybe y'all should evaluate which authentication methods are supported in these applications before picking solutions :-)

**Comment by jt15s** [comment]
@kallisti5 All of the solutions I've suggested support OAUTH. To enable this on Haiku's web infrastructure, we'll need to install some plugins or follow some steps.

Here's the plugin for Discourse that enables this: https://www.discourse.org/plugins/oauth.html
Gerrit: https://gerrit.googlesource.com/plugins/oauth/
Pootle: https://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/server/auth.html?highlight=oauth
Trac: https://trac-hacks.org/wiki/OAuth2Plugin


I don't think HaikuDepot supports OAUTH yet - here's the documentation on the security used: https://depot.haiku-os.org/__docs/security.html#security-authentication so this will need to be developed.

**Comment by kallisti5** [comment]
I like the idea of Ory.    Keycloak was a bit too complex for my liking. We really have to keep this all simple to run + manage.

**Comment by jt15s** [comment]
Yes, Ory does seem simpler to manage since it has an admin interface

**Comment by jt15s** [comment]
So, the way Ory works is that you have a range of different open-source identity products that can link in with each other or other solutions. Ory Hydra powers the OAUTH authentication: https://www.ory.sh/hydra
But the way this works is that we'll need to link it to a user account management system like Ory Kratos: https://www.ory.sh/kratos - this will include the account sign up/login experience plus the actual holding of user data.

**Comment by Forza-tng** [comment]
Seems a good choice to self-host. Are you thinking of removing the possibility to use Github as login provider?

I thibk that Nextcloud can be used as an OAuth2 provider. Nextcloud would also allow you to have shared docs, calendar and other bits, if this is interesting :) https://docs.nextcloud.com/server/25/admin_manual/configuration_server/oauth2.html

**Comment by kallisti5** [comment]
so, the main problem is sso requires a lot of time to implement... and my time is limited.  Using something like github lets us offset the management of users / sso / etc.

We also have to think about the cost and resources to run something like nextcloud, or the cost to purchase their hosted version.

**Comment by Forza-tng** [comment]
> We also have to think about the cost and resources to run something like nextcloud, or the cost to purchase their hosted version.

Indeed, while I have setup Nextcloud for my own family use, it is a lot to learn and manage. Then adding user backends, etc, is another chapter too. I have no experience with the other choices mentioned, so I can't say if they are easier/better/more suitable.

**Comment by nielx** [comment]
@kallisti5 I think the investigation has finished?

**Comment by kallisti5** [comment]
Ah yeah.    Keycloak works pretty well so far.  Even uses postgres on the backend.
I'll spin up some new issues to track integration with our various services.
