### ISSUE TITLE
Fix pootle container build

### ISSUE THREAD

**Issue by kallisti5** [haiku/infrastructure#81]
Pootle no longer builds due to an outdated translate library which references git vs https in it's git submodule.

For now, i'm manually copying docker.io/haiku/pootle:2.7.6-1 over to ghcr, however we should fix the pootle container build.

https://github.com/nielx/translate/blob/master/.gitmodules#L3

**Comment by nielx** [comment]
Fixed with https://github.com/nielx/translate/commit/e5b7ee75dc64bd0bef7f682a300f9814349051b7

I managed to successfully build and push to ghcr
