### ISSUE TITLE
Test and Deploy Trac 1.6

### ISSUE THREAD

**Issue by nielx** [haiku/infrastructure#99]
[Trac 1.6](https://trac.edgewall.org/wiki/TracDownload#Trac16StableRelease) has been released. This moves to python 3.

- [x] Update [customizations](https://github.com/haiku/trac)
- [x] Create initial pypy container build
- [x] Set up tests to validate the working of the container
- [x] Make an overview of the plugins
- [x] Check compatibility of plugins
- [x] Write an update plan

**Comment by nielx** [comment]
We have the following modules:

Must have:
- [ ] [TracAccountManager](https://trac-hacks.org/wiki/AccountManagerPlugin)
- [ ] [TracMasterTickets](https://trac-hacks.org/wiki/MasterTicketsPlugin)
- [ ] [TracRobotsTxt](http://trac-hacks.org/wiki/RobotsTxtPlugin)
- [ ] [TracSpamFilter](https://trac.edgewall.org/wiki/SpamFilter)
- [ ] [TracSubcomponents](https://github.com/nielx/trac-subcomponents)

Nice to have:
- [ ] haiku-fix-for-next-milestone - homegrown plugin
- [ ] link-haiku-cgit - homegrown plugin
- [ ] [TracPoll](https://trac-hacks.org/wiki/PollMacro)
- [ ] [TracVote](https://trac-hacks.org/wiki/VotePlugin)

**Comment by nielx** [comment]
Update: the TracSpamFilter plugin is going to be a lot of work to port over. It not only needs to be migrated to Python 3, but also needs all the templates rewritten from Genshi to Jinja2.

**Comment by nielx** [comment]
Can confirm TracSpamFilter is now up to date.

**Comment by nielx** [comment]
Patch for TracMasterTickets: https://trac-hacks.org/ticket/14336

I suspect for now we can disable TracVote and TracPoll. This means that all plugins are compatible and that I will start on the container.

**Comment by waddlesplash** [comment]
TracPoll isn't really used at this point, yes. A lot of people do use TracVote on tickets, though, and might be upset if it disappeared suddenly... I guess so long as it's only gone temporarily and we inform people of this, that may be fine.

**Comment by nielx** [comment]
> TracPoll isn't really used at this point, yes. A lot of people do use TracVote on tickets, though, and might be upset if it disappeared suddenly... I guess so long as it's only gone temporarily and we inform people of this, that may be fine.

I managed to get it working with one simple change as suggested in https://trac-hacks.org/ticket/14268 so I consider it working as well.

Will start the work on writing the update plan.

**Comment by nielx** [comment]
# Update Plan.

**Preparation**

* Enter into the running deployment and fetch all sources for the updated modules.
* Scale down the replicas to 0
* Make a backup of the DB and the volume.

**Upgrade**
* Update the image to `ghcr.io/haiku/trac:1.6.0-pypy`
* Enter the container and build and install all the updated plugins.
* Restart by scaling down the replicas to 0 and back up to 1

**Validation**
* Validate that all updated modules are running.

** Rollback plan**
* If necessary, scale down the replicas to 0
* Restore the volume and the database.
* Revert to the previous imag
* Scale back up.

**Comment by nielx** [comment]
Scheduling deployment for tomorrow (Sunday 17 March 2024 at 08:00 GMT)

**Comment by nielx** [comment]
Update complete. Lesson learned: the trac plugins do not like the wheels. Idea for the next time is to build the eggs locally and then copy them over to the production instance, that would save about 10 minutes. So far everything seems fine.
